name: CI

on: [push, pull_request]

jobs:
  ci_mingw:
      runs-on: ubuntu-latest
      container: ghcr.io/yimmenu/yimmenu:latest
      name: CI MinGW
      steps:
        - run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

        - uses: actions/checkout@v3
        
        - name: Cache build/
          id: cache-build
          uses: actions/cache@v3
          with:
            path: build
            key: ${{ runner.os }}-build
        
        - name: Build
          run: |
            cmake -DVERSION=1.3.4 -DCMAKE_BUILD_TYPE:STRING=Release -S. -Bbuild -DCROSSCOMPILE:BOOL=TRUE -DUSE_GCC:BOOL=TRUE -G Ninja
            cmake --build build --config Release
            mv build/libYimMenu.dll build/YimMenu-dev-${{github.sha}}.dll

        - name: Upload Artifact
          uses: actions/upload-artifact@v3
          with:
            name: binary-MinGW
            path: build/YimMenu-dev-*.dll

  ci_msvc:
    runs-on: windows-latest
    name: CI MSVC
    steps:
      - uses: actions/checkout@v3

      - name: Check CMake version
        run: cmake --version

      - name: Cache build/
        id: cache-build
        uses: actions/cache@v3
        with:
          path: build
          key: ${{ runner.os }}-build

      - name: Setup MSVC environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64

      - name: Generate CMake project
        run: cmake -D CMAKE_BUILD_TYPE=Release -S. -Bbuild -G Ninja

      - name: Build 64bit release DLL
        run: cmake --build ./build --config Release --target YimMenu --

      - name: Check if DLL got built
        run: if (-Not (Test-Path -path "build/YimMenu.dll")) {throw 1}

      - name: Rename DLL to YimMenu-dev-{GITHUB_SHA}.dll
        run: |
          del YimMenu-dev-*.dll
          ren YimMenu.dll YimMenu-dev-${{github.sha}}.dll
        working-directory: build/

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: binary-MSVC
          path: build/YimMenu-dev-*.dll
